# Generated by Django 5.1.6 on 2025-04-10 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fee_App', '0002_auto_20250406_1711'),
        ('StudentInformation_App', '0002_remove_studentrecords_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecords',
            name='fee',
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fee_App.fee'),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='guardian_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
