# Generated by Django 5.1.6 on 2025-04-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInformation_App', '0003_remove_studentrecords_fee_studentrecords_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='grade',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
